#include "pch.h"
#include "Material3D.h"
#include "Application.h"
#include "Canvas.h"
#include "d3dx12.h"
#include <d3dcompiler.h>

using namespace Ion::Core;

const UINT Material3D::mMaxInputParam{ 20 };
const std::map<std::string, SemanticInfo> Material3D::mSemanticStrings
{
	{ "POSITION", SemanticInfo{ InputSemantic::Position, DXGI_FORMAT_R32G32B32_FLOAT, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "NORMAL", SemanticInfo{ InputSemantic::Normal, DXGI_FORMAT_R32G32B32_FLOAT, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "TANGENT", SemanticInfo{ InputSemantic::Tangent, DXGI_FORMAT_R32G32B32_FLOAT, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "BINORMAL", SemanticInfo{ InputSemantic::Binormal, DXGI_FORMAT_R32G32B32_FLOAT, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "TEXCOORD", SemanticInfo{ InputSemantic::TexCoord, DXGI_FORMAT_R32G32_FLOAT, 8, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "COLOR", SemanticInfo{ InputSemantic::Color, DXGI_FORMAT_R32G32B32A32_FLOAT, 16, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "BLENDINDICES", SemanticInfo{ InputSemantic::BlendIndices, DXGI_FORMAT_R32G32B32A32_FLOAT, 16, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "BLENDWEIGHT", SemanticInfo{ InputSemantic::BlendWeight, DXGI_FORMAT_R32G32B32A32_FLOAT, 16, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA } },
	{ "WORLD", SemanticInfo{ InputSemantic::World, DXGI_FORMAT_R32G32B32A32_FLOAT, 16, D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA } }
};
const std::map<std::string, TextureType> Material3D::mTextureTypeStrings
{
	{ "gTextureAlbedo", TextureType::Albedo },
	{ "gTextureNormal", TextureType::Normal },
	{ "gTextureRoughness", TextureType::Roughness },
	{ "gTextureMetalness", TextureType::Metalness },
	{ "gTextureSpecular", TextureType::Specular },
	{ "gTextureHeight", TextureType::Height },
	{ "gTextureOpacity", TextureType::Opacity },
	{ "gTextureAmbientOcclusion", TextureType::AmbientOcclusion },
	{ "gTextureRefraction", TextureType::Refraction },
	{ "gTextureSelfIllumination", TextureType::SelfIllumination }
};

Material3D::Material3D(Application* pApplication, const std::string& name)
	: mIsInitialized{ false }
	, mpApplication{ pApplication }
	, mName{ name }
	, mRS{}
	, mVS{}
	, mPS{}
	, mpRootSignature{}
	, mpPipelineState{}
	, mSigParDescs{}
	, mpInputElementDescs{ nullptr }
	, mConstantBufferCount{ 0 }
	, mInputElementCount{ 0 }
	, mLayoutSize{ 0 }
	, mpCanvasViewCs{}
{
	auto pDevice{ mpApplication->GetDevice() };
#ifdef _DEBUG
	std::string dir{ "Debug" };
#else
	std::string dir{ "Release" };
#endif

	// Build Root Signature
	{
		std::string str{ "../x64/" + dir + "/" + mName + "_rs.cso" };
		std::wstring wstr(str.begin(), str.end());
		ThrowIfFailed(D3DReadFileToBlob(wstr.c_str(), &mRS));
		ThrowIfFailed(pDevice->CreateRootSignature(0, mRS->GetBufferPointer(), mRS->GetBufferSize(), IID_PPV_ARGS(&mpRootSignature)));
	}

	// Shaders
	{
		std::string str{ "../x64/" + dir + "/" + mName + "_vs.cso" };
		std::wstring wstr(str.begin(), str.end());
		ThrowIfFailed(D3DReadFileToBlob(wstr.c_str(), &mVS));
	}
	{
		std::string str{ "../x64/" + dir + "/" + mName + "_ps.cso" };
		std::wstring wstr(str.begin(), str.end());
		ThrowIfFailed(D3DReadFileToBlob(wstr.c_str(), &mPS));
	}

	ID3D12ShaderReflection* pVSReflector{ nullptr };
	ThrowIfFailed(D3DReflect(mVS->GetBufferPointer(), mVS->GetBufferSize(), IID_PPV_ARGS(&pVSReflector)));
	// Build texture types set supported by shader
	ID3D12ShaderReflection* pPSReflector{ nullptr };
	ThrowIfFailed(D3DReflect(mPS->GetBufferPointer(), mPS->GetBufferSize(), IID_PPV_ARGS(&pPSReflector)));
	D3D12_SHADER_INPUT_BIND_DESC shaderBindDesc{};
	for (auto& pair : mTextureTypeStrings)
		if (pPSReflector->GetResourceBindingDescByName(pair.first.c_str(), &shaderBindDesc) == S_OK)
			mTextureTypes.emplace(pair.second);
	// Read & build Input layout from Vertex shader
	while (pVSReflector->GetInputParameterDesc(mInputElementCount, &mSigParDescs[mInputElementCount]) == S_OK)
		++mInputElementCount;
	mpInputElementDescs = new D3D12_INPUT_ELEMENT_DESC[mInputElementCount];
	UINT svInstanceID{ 0 };
	for (UINT i{ 0 }; i < mInputElementCount; ++i)
	{
		// SV_InstanceID is generated by DirectX and should be last
		if (std::strcmp(mSigParDescs[i].SemanticName, "SV_InstanceID") == 0)
		{
			svInstanceID = 1;
			continue;
		}
		const SemanticInfo& semanticInfo{ mSemanticStrings.at(mSigParDescs[i].SemanticName) };
		mpInputElementDescs[i] = {
			mSigParDescs[i].SemanticName,
			mSigParDescs[i].SemanticIndex,
			semanticInfo.format,
			0,
			mLayoutSize,
			semanticInfo.inputClassification,
			0 };
		mLayoutSize += semanticInfo.offset;
	}
	mInputElementCount -= svInstanceID;
}

Material3D::~Material3D()
{
	if (mpInputElementDescs != nullptr)
		delete[] mpInputElementDescs;
}

void Material3D::Initialize()
{
	if (mIsInitialized)
		return;
	if (mpInputElementDescs == nullptr)
		return;
	auto pDxgiFactory{ mpApplication->GetDxgiFactory() };
	auto pDevice{ mpApplication->GetDevice() };
	auto pCommandAllocator{ mpApplication->GetCommandAllocator() };

	// Build Pipeline State
	{
		D3D12_RASTERIZER_DESC rasDesc{};
		rasDesc.FillMode = D3D12_FILL_MODE_SOLID;
		rasDesc.CullMode = D3D12_CULL_MODE_BACK;
		D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc{};
		psoDesc.InputLayout = { mpInputElementDescs, mInputElementCount };
		psoDesc.pRootSignature = mpRootSignature.Get();
		psoDesc.VS = CD3DX12_SHADER_BYTECODE(mVS.Get());
		psoDesc.PS = CD3DX12_SHADER_BYTECODE(mPS.Get());
		psoDesc.RasterizerState = rasDesc;
		psoDesc.BlendState = CD3DX12_BLEND_DESC(D3D12_DEFAULT);
		psoDesc.DepthStencilState = CD3DX12_DEPTH_STENCIL_DESC(D3D12_DEFAULT);
		psoDesc.SampleMask = UINT_MAX;
		psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
		psoDesc.NumRenderTargets = 1;
		psoDesc.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
		psoDesc.DSVFormat = DXGI_FORMAT_D32_FLOAT;
		psoDesc.SampleDesc.Count = 1;
		ThrowIfFailed(pDevice->CreateGraphicsPipelineState(&psoDesc, IID_PPV_ARGS(&mpPipelineState)));
	}
	mIsInitialized = true;
}

void Material3D::Render(Canvas* pCanvas)
{
	auto pCommandAllocator{ mpApplication->GetCommandAllocator() };
	auto pGraphicsCommandList{ pCanvas->GetGraphicsCommandList() };

	pGraphicsCommandList->SetPipelineState(mpPipelineState.Get());
	pGraphicsCommandList->SetGraphicsRootSignature(mpRootSignature.Get());

	pCanvas->SetDescriptor();

	for (auto pViewC : mpCanvasViewCs[pCanvas])
		pViewC->Render(pCanvas, this);
}

const Microsoft::WRL::ComPtr<ID3D12RootSignature>& Material3D::GetRootSignature()
{
	return mpRootSignature;
}

const Microsoft::WRL::ComPtr<ID3D12PipelineState>& Material3D::GetPipelineState()
{
	return mpPipelineState;
}

D3D12_INPUT_ELEMENT_DESC* Material3D::GetInputElementDescs()
{
	return mpInputElementDescs;
}

UINT Material3D::GetInputElementCount() const
{
	return mInputElementCount;
}

UINT Material3D::GetLayoutSize() const
{
	return mLayoutSize;
}

const std::set<TextureType>& Material3D::GetTextureTypeSet() const
{
	return mTextureTypes;
}

void Material3D::AddViewC(Canvas* pCanvas, ViewC* pViewC)
{
	mpCanvasViewCs[pCanvas].emplace_back(pViewC);
}

const std::map<std::string, SemanticInfo>& Material3D::GetSemanticStrings()
{
	return mSemanticStrings;
}
